apiVersion: v2
name: kafka-bridge
description: Http => Kafka bridge with support for Avro
type: application
version: 0.0.10
appVersion: "0.0.10"
maintainers:
  - name: nico-stoppel
    email: nico.stoppel@neuland-bfi.de
