name: Manually build and publish container image

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-publish-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - run: >-
          mvn
          versions:set -DnewVersion=$( git describe --tags --abbrev=0 )-SNAPSHOT-$( git rev-parse --short HEAD )
          versions:commit
          --no-transfer-progress
      - name: Test
        run: mvn test --no-transfer-progress
      - name: Log in to GitHub Packages container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and publish container image
        run: mvn jib:build --no-transfer-progress
